### ISSUE TITLE
Support compatibility with 4.7.x

### ISSUE THREAD

**Issue by joemcl** [twomice/com.joineryhq.activityical#21] opened 2017-06-02 19:56 UTC
This looks really useful. Thanks Allen! 
Is it compatible with Civi 4.7.x? 
- If so, please update info.xml and https://civicrm.org/extensions/civicrm-activity-icalendar-feed . 
- If not, any ETA on compatibility?

**Comment by twomice** [comment] 2017-06-02 20:04
I haven't used in on 4.7 yet but I have a feeling it would be fine. If you have a chance, please try it, and post any issues here.

**Comment by twomice** [comment] 2017-06-02 20:04
I've renamed this ticket to be a placeholder for discussing the status of a 4.7 release. Thanks, @joemcl !

**Comment by joemcl** [comment] 2017-06-03 01:11
Cool, I'll test it on my dev instance running 4.7.18

**Comment by twomice** [comment] 2017-06-05 13:46
Thanks, @joemcl !

**Comment by wintermoor** [comment] 2017-07-24 14:01
Installed on a fresh 4.7.22 CiviCRM and is not working: Tab "Calender" shows at Contacts, but isn't populated with data. 

Does it need "clean URLs" with mod_rewrite or will it work out-of-the-box with Drupal-URLs?

**Comment by petednz** [comment] 2017-12-14 00:01
I just tried installing on 4.7.27. Upon install i got msg "Extension Key does not match expected standard" - does that make sense to anyone?

**Comment by twomice** [comment] 2017-12-18 16:03
@petednz I've tried that just now and can't reproduce. Any chance you have more specific steps?

**Comment by twomice** [comment] 2017-12-18 16:06
@wintermoor Sorry I didn't see your (months old) comment until now. I'm unsure what you mean by 'Tab "Calendar" at Contactcs'.  This extension doesn't create a tab named "Calendar" or a calendar. It does create, for contacts who added to the relevant group(s), links labeled "Feed" and "Details" under the Activities tab on the Contact page.  If you have more details, please post them and I'll try to help.

**Comment by twomice** [comment] 2017-12-18 16:20
@petednz I suspect you're seeing this in action: https://issues.civicrm.org/jira/browse/CRM-21388 (issue in 4.7.27, fixed in 4.7.28)

**Comment by twomice** [comment] 2017-12-18 16:51
My testing indicates this extension works fine with CiviCRM 4.7. I've indicated such and cut a new release, v1.4.  I'm closing this issue now. If you have specific problems in CiviCRM 4.7, please open a new issue.

**Closed by twomice** 2017-12-18 16:51 UTC

**Comment by petednz** [comment] 2017-12-18 19:21
Great. Thanks
